name: autotrie
description: A auto-completion engine for Dart/Flutter, based around an optimized Trie implementation.
version: 0.1.2
homepage: https://github.com/AKushWarrior/autotrie
repository: https://github.com/AKushWarrior/autotrie
issue_tracker: https://github.com/AKushWarrior/autotrie/issues

environment:
  sdk: '>=2.1.0 <3.0.0'

#dependencies:

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
