name: autotrie
description: A auto-completion engine for Dart/Flutter, based around an optimized Trie implementation.
version: 1.0.0+1
homepage: https://github.com/AKushWarrior/autotrie
repository: https://github.com/AKushWarrior/autotrie
issue_tracker: https://github.com/AKushWarrior/autotrie/issues

environment:
  sdk: '>=2.6.0 <3.0.0'

dependencies:
  hive: ^1.4.3
  meta: ^1.1.1

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
